#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Start Commitizen if normal commit was triggered (not merge, rebase, etc.)
# Only if terminal is interactive
if [ -t 1 ]; then
  exec < /dev/tty && npx cz --hook || true
fi